version: "3"

services:
  status_flask:
    build: .
    image: server_status_flask
    restart: always
    network_mode: host
    volumes:
        - "./app:/app"
    command: tail -F anything  # keeps the container running without running the flask app