version: "3"

services:
  status_flask:
    build: .
    image: server_status_flask
    restart: always
    ports:
        - "80:80"
    # network_mode: host
    volumes:
        - "./app:/app"
    command: python /app/flask_app.py 80 False

networks:
  default:
    external:
      name:
